from collections import deque

def test_sequence(p, moves):
    """Test what sequence is generated by the given moves"""
    dq = deque(p)
    result = []
    
    for move in moves:
        if move == 'L':
            result.append(dq.popleft())
        else:
            result.append(dq.pop())
    
    return result

def is_bad_sequence(seq):
    """Check if sequence contains 5 consecutive increasing or decreasing elements"""
    if len(seq) < 5:
        return False
    for i in range(len(seq) - 4):
        if all(seq[j] < seq[j+1] for j in range(i, i+4)):
            print(f"Bad increasing subsequence at positions {i}-{i+4}: {seq[i:i+5]}")
            return True
    for i in range(len(seq) - 4):
        if all(seq[j] > seq[j+1] for j in range(i, i+4)):
            print(f"Bad decreasing subsequence at positions {i}-{i+4}: {seq[i:i+5]}")
            return True
    return False

def current_solve(p):
    """Current algorithm"""
    dq = deque(p)
    q = []

    for i in range(min(6, len(p))):
        left = dq[0]
        right = dq[-1]

        if i % 2 == 0:
            if left < right:
                dq.popleft()
                q.append('L')
            else:
                dq.pop()
                q.append('R')
        else:
            if left > right:
                dq.popleft()
                q.append('L')
            else:
                dq.pop()
                q.append('R')

    while dq:
        dq.popleft()
        q.append('L')

    return ''.join(q)

# Test case that could cause issues - sorted array
test_case = list(range(1, 11))  # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(f"Test case: {test_case}")

moves = current_solve(test_case)
print(f"Moves: {moves}")

result = test_sequence(test_case, moves)
print(f"Result sequence: {result}")
print(f"Is bad: {is_bad_sequence(result)}")
print()

# Another problematic case - reverse sorted
test_case2 = list(range(10, 0, -1))  # [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
print(f"Test case 2: {test_case2}")

moves2 = current_solve(test_case2)
print(f"Moves: {moves2}")

result2 = test_sequence(test_case2, moves2)
print(f"Result sequence: {result2}")
print(f"Is bad: {is_bad_sequence(result2)}")
